controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    # Common controllers (shared)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # Robot 409 controllers
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # Robot 410 specific controllers
    robot_410_scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

# Robot 409 Controller Parameters (default controllers)
joint_state_broadcaster:
  ros__parameters:
    joints:
      - 409_ur5e_shoulder_pan_joint
      - 409_ur5e_shoulder_lift_joint
      - 409_ur5e_elbow_joint
      - 409_ur5e_wrist_1_joint
      - 409_ur5e_wrist_2_joint
      - 409_ur5e_wrist_3_joint
      - 410_ur5e_shoulder_pan_joint
      - 410_ur5e_shoulder_lift_joint
      - 410_ur5e_elbow_joint
      - 410_ur5e_wrist_1_joint
      - 410_ur5e_wrist_2_joint
      - 410_ur5e_wrist_3_joint
    interfaces:
      - position
      - velocity

io_and_status_controller:
  ros__parameters:
    tf_prefix: "409_ur5e_"
    robot_status_pub_rate: 10.0

speed_scaling_state_broadcaster:
  ros__parameters:
    tf_prefix: "409_ur5e_"

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: 409_ur5e_tcp_fts_sensor
    state_interface_names:
      - 409_ur5e_tcp_fts_sensor/force.x
      - 409_ur5e_tcp_fts_sensor/force.y
      - 409_ur5e_tcp_fts_sensor/force.z
      - 409_ur5e_tcp_fts_sensor/torque.x
      - 409_ur5e_tcp_fts_sensor/torque.y
      - 409_ur5e_tcp_fts_sensor/torque.z
    frame_id: 409_ur5e_tool0

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - 409_ur5e_shoulder_pan_joint
      - 409_ur5e_shoulder_lift_joint
      - 409_ur5e_elbow_joint
      - 409_ur5e_wrist_1_joint
      - 409_ur5e_wrist_2_joint
      - 409_ur5e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 2.0
      409_ur5e_shoulder_pan_joint: { trajectory: 0.5, goal: 0.2 }
      409_ur5e_shoulder_lift_joint: { trajectory: 0.5, goal: 0.2 }
      409_ur5e_elbow_joint: { trajectory: 0.5, goal: 0.2 }
      409_ur5e_wrist_1_joint: { trajectory: 0.5, goal: 0.2 }
      409_ur5e_wrist_2_joint: { trajectory: 0.5, goal: 0.2 }
      409_ur5e_wrist_3_joint: { trajectory: 0.5, goal: 0.2 }
    speed_scaling_interface_name: 409_ur5e_speed_scaling/speed_scaling_factor

# Robot 410 Controller Parameters
robot_410_scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - 410_ur5e_shoulder_pan_joint
      - 410_ur5e_shoulder_lift_joint
      - 410_ur5e_elbow_joint
      - 410_ur5e_wrist_1_joint
      - 410_ur5e_wrist_2_joint
      - 410_ur5e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 2.0
      410_ur5e_shoulder_pan_joint: { trajectory: 0.5, goal: 0.2 }
      410_ur5e_shoulder_lift_joint: { trajectory: 0.5, goal: 0.2 }
      410_ur5e_elbow_joint: { trajectory: 0.5, goal: 0.2 }
      410_ur5e_wrist_1_joint: { trajectory: 0.5, goal: 0.2 }
      410_ur5e_wrist_2_joint: { trajectory: 0.5, goal: 0.2 }
      410_ur5e_wrist_3_joint: { trajectory: 0.5, goal: 0.2 }
    speed_scaling_interface_name: 410_ur5e_speed_scaling/speed_scaling_factor 