# Default initial positions for my_robot_cell's ros2_control fake system

initial_positions:
  409_ur5e_elbow_joint: 0
  409_ur5e_shoulder_lift_joint: -1.5708
  409_ur5e_shoulder_pan_joint: 0
  409_ur5e_wrist_1_joint: -1.5708
  409_ur5e_wrist_2_joint: 0
  409_ur5e_wrist_3_joint: 0
  410_ur5e_elbow_joint: 0
  410_ur5e_shoulder_lift_joint: -1.5708
  410_ur5e_shoulder_pan_joint: 0
  410_ur5e_wrist_1_joint: -1.5708
  410_ur5e_wrist_2_joint: 0
  410_ur5e_wrist_3_joint: 0