# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

trajectory_execution:
  allowed_execution_duration_scaling: 2.0
  allowed_goal_duration_margin: 1.0
  allowed_start_tolerance: 0.05
  execution_duration_monitoring: false

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - robot_410_scaled_joint_trajectory_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - 409_ur5e_shoulder_pan_joint
      - 409_ur5e_shoulder_lift_joint
      - 409_ur5e_elbow_joint
      - 409_ur5e_wrist_1_joint
      - 409_ur5e_wrist_2_joint
      - 409_ur5e_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true

  robot_410_scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - 410_ur5e_shoulder_pan_joint
      - 410_ur5e_shoulder_lift_joint
      - 410_ur5e_elbow_joint
      - 410_ur5e_wrist_1_joint
      - 410_ur5e_wrist_2_joint
      - 410_ur5e_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: false