# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    409_ur5e_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    410_ur5e_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

409_ur5e_arm_controller:
  ros__parameters:
    joints:
      - 409_ur5e_shoulder_pan_joint
      - 409_ur5e_shoulder_lift_joint
      - 409_ur5e_elbow_joint
      - 409_ur5e_wrist_1_joint
      - 409_ur5e_wrist_2_joint
      - 409_ur5e_wrist_3_joint
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true
410_ur5e_arm_controller:
  ros__parameters:
    joints:
      - 410_ur5e_shoulder_pan_joint
      - 410_ur5e_shoulder_lift_joint
      - 410_ur5e_elbow_joint
      - 410_ur5e_wrist_1_joint
      - 410_ur5e_wrist_2_joint
      - 410_ur5e_wrist_3_joint
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    allow_nonzero_velocity_at_trajectory_end: true